// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBreEFt_9V5tPIrck2fuNscLzgHGcoQKFo',
    appId: '1:782408087540:web:d7daf9600f2db8834aaba1',
    messagingSenderId: '782408087540',
    projectId: 'company-cced4',
    authDomain: 'company-cced4.firebaseapp.com',
    databaseURL: 'https://company-cced4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'company-cced4.appspot.com',
    measurementId: 'G-5SNBXRP45V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeCI7VTrf7tQGiyJ3yiEOzLTW88dbdgqU',
    appId: '1:782408087540:android:f54440b6693101264aaba1',
    messagingSenderId: '782408087540',
    projectId: 'company-cced4',
    databaseURL: 'https://company-cced4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'company-cced4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpTD0hSt4Fwi3cBKNnj9q4AFbzDprcmaM',
    appId: '1:782408087540:ios:dad1dc93c30b0eb24aaba1',
    messagingSenderId: '782408087540',
    projectId: 'company-cced4',
    databaseURL: 'https://company-cced4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'company-cced4.appspot.com',
    iosBundleId: 'com.example.company',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpTD0hSt4Fwi3cBKNnj9q4AFbzDprcmaM',
    appId: '1:782408087540:ios:dad1dc93c30b0eb24aaba1',
    messagingSenderId: '782408087540',
    projectId: 'company-cced4',
    databaseURL: 'https://company-cced4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'company-cced4.appspot.com',
    iosBundleId: 'com.example.company',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBreEFt_9V5tPIrck2fuNscLzgHGcoQKFo',
    appId: '1:782408087540:web:02a13f10142af4cc4aaba1',
    messagingSenderId: '782408087540',
    projectId: 'company-cced4',
    authDomain: 'company-cced4.firebaseapp.com',
    databaseURL: 'https://company-cced4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'company-cced4.appspot.com',
    measurementId: 'G-BVQS0RRW0P',
  );
}
